# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d077a7ac0edcd444587dd6ef8f04372c840dacc6c93e03fa25bd7a2b825fd73754fe459d9fdb836d5921b1fca5fbfcb0222257a597b29fd4c48d183304755682

test:
  secret_key_base: 8b9d88499bffb403de0ca67a2f8627148064390f605bc5de06a92f4dc001cb7a660d0894b3c4fc8d4aa1ed9292d9be85ec737664c1aa2b076e8f7c540d090773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
